### ISSUE TITLE
pigen doesnt annotate all isoforms 

### ISSUE THREAD

**Issue by roofya** [PacificBiosciences/pigeon#1]
Hi

Im using this command 
pigeon classify my.sorted.gff  ref/GRCh38.p13/gencode.v43.annotation.gtf ref/GRCh38.p13/GRCh38.primary_assembly.genome.fa

and the error was that the | 20230215 12:49:42.625 | FATAL | pigeon classify ERROR: file: '../../ref/GRCh38.p13/GRCh38.primary_assembly.genome.fa.fai' does not exist

Then I have indexed GRCh38.primary_assembly.genome.fa by samtools. and then run the command. I got the classification.txt file and then these three output. 
*.filtered_lite_classification.txt
*.filtered_lite_junctions.txt
*.filtered_lite_reasons.txt

The problem is that no isoform founds for some of my interested genes. However I have checked the gtf of reference genome and the genes were annotated. Please advise why my.sorted.gff file doesnt annotate properly?

Thank you

**Comment by jmattick** [comment]
Hi @luckyvivi. We have just released `pigeon v1.2.0` on Bioconda. Please give that a try. If you are still having issues please upload a minimal reproducible example.
