### ISSUE TITLE
using NCBI refseq annotation as input for pigeon?

### ISSUE THREAD

**Issue by chunlinxiao** [PacificBiosciences/pigeon#10]
Current "pigeon classify" just takes gencode.annotation.gtf as one of the inputs - is it possible to allow using NCBI refseq annotation (gtf) as input?

thanks

**Comment by jmattick** [comment]
Hi @chunlinxiao. You can use other annotations as long as they meet the specifications here https://isoseq.how/classification/pigeon-annotation.html
We just released pigeon `v1.2.0` which has a new `pigeon prepare` tool that will validate your annotation. 
https://isoseq.how/classification/workflow.html#prepare-reference-files-for-pigeon
