### ISSUE TITLE
Features requires in pigeon

### ISSUE THREAD

**Issue by unique379r** [PacificBiosciences/pigeon#12]
Hi
I am requesting if you can adapt some features in pigeon:
1. Produce summary.txt also for filter step, similar to the one you do in classify step.
2. Require annotation of generated gff output from filter/classify.
3. It would be awesome if you can generate the fasta/fastq in  pigeon classify/filter step. Similar to the one SQANTI3 is generating. 
4. Require more filtering control and options like ML filter in SQANTI3.
5. It may also fruitful if you can have option to rescue TP events which may have been filtered. Similar to SQANTI3.
6. It would be great if you have any options to compare two or more gff output.

**Comment by jmattick** [comment]
Thanks for the feedback @unique379r. We will discuss these feature requests internally.
