### ISSUE TITLE
Documentation about make-seurat output

### ISSUE THREAD

**Issue by Fougere87** [PacificBiosciences/pigeon#13]
Hi, 
I can't find any documentation about how pigeon counts isoforms and genes when using make-seurat command. 

What exactly is in the gene_seurat and isoform_seurat? Are genes a sum/merge of all isoforms associated to an annotated gene ?
If it is the case, then how are isoforms asociated to a gene ? 

How are treated intronic reads ? 

Thank you by advance ! 
Best regards, 
C.

**Comment by greensii** [comment]
agree with the request above, and additionally it would be helpful to have documentation for the `annotated-prefilter.info.csv` file in the newest pigeon version - what does `pass_pigeon_filter` mean?

**Comment by pezmaster31** [comment]
@Fougere87 @greensii Agreed, we will update the documentation section for the `make-seurat` output files. 

@Fougere87 

High-level summary:
* `genes_seurat/barcodes.tsv` : list of observed barcode sequences
* `genes_seurat/genes.tsv` : observed gene annotations (as identified by isoseq collapse & pigeon classify)
* `genes_seurat/matrix.mtx` : maps each {gene,barcode} pair with barcode counts

* `isoforms_seurat/barcodes.tsv` : list of observed barcode sequences
* `isoforms_seurat/genes.tsv` : observed gene annotations, per unique transcript (as identified by isoseq collapse & pigeon classify)
* `isoforms_seurat/matrix.mtx` : maps each {gene,barcode} pair with barcode counts

Please take a look [here](https://isoseq.how/umi/tertiary-analysis.html) to see how these files are used in a few downstream analysis tools.

w.r.t. **intronic reads**: both "genic_intron" and "intergenic" classifications are excluded from `make-seurat` counts, unless the command is run with the `--keep-novel-genes` option.

@greensii 

The typical intended workflow is to run `make-seurat` on filtered data, which generates the `annotated.info.csv`. For troubleshooting purposes, we found it useful to get counts for _all_ data as well. So `make-seurat` now also generates an `annotation-prefilter.info.csv` if the unfiltered classification file is in the same directory as the filtered one. 

The `pass_pigeon_filter` flag in these files therefore indicates whether a molecule's classification passed or failed filtering. For the `annotation.info.csv` file this will always be "PASS", and for the prefiltered one, either "PASS" or "FAIL".
