### ISSUE TITLE
Pigeon does not respect set ulimits

### ISSUE THREAD

**Issue by markb729** [PacificBiosciences/pigeon#14]
Using smrtlink-release_12.0.0.177059 command-line tools, I was encountering an error when processing bulk cell Iso-Seq data, specifically with pigeon sort on the output of isoseq3 cluster:

`pigeon sort sample01_clustered.hq.mapped.gff -o sample01_clustered.hq.mapped.sorted.gff`
| 20231026 14:35:41.788 | FATAL | pigeon sort ERROR: 1 - could not read GFF file

The error message is not informative but investigation indicated that pigeon separated annotation entries by reference seqname, outputting large numbers of files to disk, but many fewer than the total number contained within the reference. The subset of files outputted just happened to be 1023, one less than a typical ulimit of 1024. 

Increasing the open file limit with a `ulimit -n ` larger than the number of reference seqnames eliminates this problem and results in a correctly sorted gff.

_NB: this will only affect users with reference genomes containing large numbers of contigs or scaffold (at least larger than the set ulimit, which can vary greatly from machine to machine), not chromosome-level (high-quality) assemblies._

pigeon 1.0.99 (commit -v0.1.0-33-ge15e62b)

Using:
  pbbam     : 2.3.0 (commit v2.3.0)
  pbcopper  : 2.2.0 (commit v2.2.0)
  boost     : 1.76
  htslib    : 1.13
  zlib      : 1.2.11

**Comment by armintoepfer** [comment]
That `ulimit` also include file handles for reading.

The SMRT Link troubleshooting guide recommends a higher `ulimit -n` https://www.pacb.com/wp-content/uploads/SMRT_Link_Troubleshooting_Guide_v80.pdf
