### ISSUE TITLE
Documentation for classification output

### ISSUE THREAD

**Issue by sum732** [PacificBiosciences/pigeon#4]
Hello,

I am wondering if there is documentations to understand all the outputs. How are they different from SQANTI3 output. 

There are some subtle differences, for example, the last col from SQANTI3 (post filtering) is ` filter_result`. From Pigeon its `cell_barcodes`. 

I have not exhaustively compared the outputs to know what else has changed. 

Additionally, for the same long read sample, from SQANTI3
```
total isoform, FSM=15,340
```
From Pigeon its 
```
full-splice_match=11,316
```
It would be great to know what has changed, understand the output, and also get PDF/HTML summaries like SQANTI3.

Best,
SM

**Comment by sum732** [comment]
I found the doc that explains, sorry somehow i missed this:
```
https://isoseq.how/classification/pigeon-output.html
```

**Comment by armintoepfer** [comment]
It's not a bug-compatible port, differences are expected. PDF or HTML outputs are not planned.

Let me ping @derekwbarnett @jmattick @Magdoll about expected differences in FSM.
