### ISSUE TITLE
pigeon classify shows all intergenic

### ISSUE THREAD

**Issue by luckyvivi** [PacificBiosciences/pigeon#7]
Hi, I run pigeon classify with ⬇️
pigeon classify isoforms.gff annotations.gtf reference.fa, but yield the summary file showing all isoform belongs to the intergenic region. Could you please help me find the reason?
<img width="534" alt="image" src="https://github.com/PacificBiosciences/pigeon/assets/88259108/12864ed6-e348-419e-9992-ef1aef0e6eae">

**Comment by jmattick** [comment]
Hi @luckyvivi. We have just released `pigeon v1.2.0` on Bioconda. Please give that a try. If you are still having issues please upload a minimal reproducible example.
