### ISSUE TITLE
how to plot pigeon report txt similar to sqanti3?

### ISSUE THREAD

**Issue by unique379r** [PacificBiosciences/pigeon#8]
Hi
is there way of plotting isoform classifications generated by pigeon similar to sqanti3 ike html or pdf?

thanks

**Comment by zeeev** [comment]
Hi @unique379r,

checkout https://github.com/ConesaLab/SQANTI3/tree/master/utilities/report_pigeon

**Comment by unique379r** [comment]
Thanks, needed some tuning on that but works. However, no filter information reported in the plots like before and after filtering similar to sqanti3.
