### ISSUE TITLE
Which option should i should in pigeon to use " intropolis (exon-exon junctions )" ? 

### ISSUE THREAD

**Issue by unique379r** [PacificBiosciences/pigeon#9]
Hi
I am trying to see if i can use the external ref like "exon-exon junctions i.e. intropolis" in **"pigeon classify"** but unfortunately i am unable to find any option to use it, neither you tutorial uses it (https://isoseq.how/classification/workflow.html).

Please suggest.

Thanks
Rupesh Kesharwani

**Comment by jmattick** [comment]
Hi @unique379r  You can use this pigeon option. 
```
  -c,--coverage            FILE  Junction coverage data. Associated .pgi file is required. Use 'pigeon index' to
                                 generate one.
```
Thanks for pointing out that it's missing in the docs.
